import { defineConfig } from "vite";
import motionCanvas from "@motion-canvas/vite-plugin";
import ffmpeg from "@motion-canvas/ffmpeg";

export default defineConfig({
  // server: {
  //   fs: {
  //     // let it load external files
  //     strict: false,
  //   },
  // },
  plugins: [
    motionCanvas({
      project: [
        // "./src/crap.ts",
        // "./src/scenes/audio_example/audio_example.ts",
        // "./src/scenes/nextgen/nextgen.ts",
        // // "./src/utils/utilsDemoProject.ts",
        // // "./src/coordinates.ts",
        // // "./src/regression440_demo.ts",
        // // "./src/play_all_day_demo.ts",
        // // "./src/scenes/play_all_day/play_all_day.ts",
        // "./src/example.ts",
        // // "./src/rolltext.ts",
        // // "./src/regression440.ts",
        // // "./src/plotting.ts",
        // // "./src/scenes/tpd_no_replacement/tpd_no_replacement_demo.ts",
        // // "./src/scenes/tpd_no_replacement/tpd_no_replacement.ts",
        // "./src/scenes/boxcars/boxcars_demo.ts",
        // // "./src/scenes/boxcars/boxcars.ts",
        // // "./src/scenes/sixeight_lowroller/sixeight_lowroller_demo.ts",
        // // "./src/scenes/sixeight_lowroller/sixeight_lowroller.ts",
        // // "./src/scenes/skill66/skill66_demo.ts",
        // // "./src/scenes/skill66/skill66.ts",
        // "./src/components/plot/plotProject.ts",
        // // "./src/scenes/skill66baseline/skill66baseline.ts",
        // // "./src/scenes/skill66baseline/skill66baseline_demo.ts",
        // // "./src/scenes/jungle/jungle_demo.ts",
        // // "./src/scenes/jungle/jungle.ts",
        // "./src/scenes/skill66halfpress/skill66halfpress.ts",
        // // "./src/scenes/skill66halfpress/skill66halfpress_demo.ts",
        // "./src/scenes/push_it/push_it_demo.ts",
        // "./src/scenes/push_it/pushit.ts",
        // "./src/scenes/dp678/dp678_demo.ts",
        // "./src/scenes/dp678hedge/dp678hedge_demo.ts",
        // "./src/scenes/even_steven/even_steven_demo.ts",
        // "./src/scenes/even_steven/even_steven.ts",
        // "./src/scenes/three_hand_band/three_hand_band_demo.ts",
        // "./src/scenes/three_point_molly/three_point_molly_demo.ts",
        // "./src/scenes/three_point_molly/three_point_molly.ts",
        // "./src/scenes/wgs_tweak/wgs_tweak_demo.ts",
        // "./src/scenes/fifty_for_one/fifty_for_one_demo.ts",
        // "./src/scenes/fifty_for_one/fifty_for_one.ts",
        // "./src/scenes/all_day_678/all_day_678_demo.ts",
        // "./src/scenes/all_day_678/all_day_678.ts",
        // "./src/scenes/field_ultimate/field_ultimate.ts",
        // "./src/scenes/field_ultimate/field_ultimate_demo.ts",
        // "./src/scenes/dd_135_across/dd_135_across_demo.ts",
        // "./src/scenes/dd_135_across/dd_135_across.ts"
        // "./src/scenes/lay_the_point_100/lay_the_point_100_demo.ts",
        // "./src/scenes/lay_the_point_100/lay_the_point_100.ts",
        // "./src/scenes/lay_the_point_proper/lay_the_point_proper.ts",
        // "./src/scenes/lay_the_point_proper/lay_the_point_proper_demo.ts",
        // "./src/scenes/lay_the_point_jimmy_vid/lay_the_point_jimmy.ts",
        // "./src/scenes/hybrid_reverse_arnold_ladder/hybrid_reverse_arnold_ladder_demo.ts",
        // "./src/scenes/hybrid_lay_the_point/hybrid_lay_the_point.ts",
        // "./src/scenes/hybrid_lay_the_point/hybrid_lay_the_point_demo.ts",
        // "./src/scenes/hybrid_model_brian/hybrid_model_brian_demo.ts",
        // "./src/scenes/three_point_dolly/three_point_dolly_demo.ts",
        "./src/scenes/three_point_dolly/three_point_dolly.ts",
        "./src/scenes/ats/ats.ts",
        "./src/scenes/arnold/arnold.ts",
        "./src/scenes/arnold/arnold_demo.ts",
        "./src/scenes/newhist/newhist.ts",
        "./src/scenes/cover4/cover4.ts",
        "./src/scenes/cover4press/cover4press.ts",
        "./src/scenes/cover4press/cover4press_demo.ts",
        "./src/scenes/cover4/cover4_demo.ts",
        "./src/scenes/cold_table_steroids/cold_table_steroids.ts",
        "./src/scenes/cold_table_steroids/cold_table_steroids_demo.ts",
        "./src/scenes/one_hit_wonder/one_hit_wonder_demo.ts",
        "./src/scenes/sonic_the_hedgehog/sonic_the_hedgehog_demo.ts",
        "./src/scenes/three_point_molly_working/three_point_molly_working_demo.ts",
        "./src/scenes/three_point_molly_working/three_point_molly_working.ts",
        "./src/scenes/theone/theone_demo.ts",
        "./src/scenes/p16/p16_demo.ts",
        "./src/scenes/four_five_pt_molly/four_five_pt_molly_demo.ts",
        "./src/scenes/sonic_the_hedgehog/sonic_the_hedgehog.ts",
        "./src/scenes/ats_hedge/ats_hedge.ts",
      ],
    }),
    ffmpeg(),
  ],
});
