import { Vector2 } from "@motion-canvas/core";

export enum c {
  PLAYER = "PLAYER",
  DEALER = "DEALER",

  PASSLINE = "PASSLINE",
  PASSLINEODDS = "PASSLINE_ODDS",

  DONTPASS = "DONTPASS",
  DONTPASSODDS = "DONTPASSODDS",

  FIELD = "FIELD",

  COME = "COME",
  COME4 = "COME4",
  COME5 = "COME5",
  COME6 = "COME6",
  COME8 = "COME8",
  COME9 = "COME9",
  COME10 = "COME10",

  DONTCOME = "DONTCOME",
  DONTCOME4 = "DONTCOME4",
  DONTCOME5 = "DONTCOME5",
  DONTCOME6 = "DONTCOME6",
  DONTCOME8 = "DONTCOME8",
  DONTCOME9 = "DONTCOME9",
  DONTCOME10 = "DONTCOME10",

  DONTCOME4ODDS = "DONTCOME4ODDS",
  DONTCOME5ODDS = "DONTCOME5ODDS",
  DONTCOME6ODDS = "DONTCOME6ODDS",
  DONTCOME8ODDS = "DONTCOME8ODDS",
  DONTCOME9ODDS = "DONTCOME9ODDS",
  DONTCOME10ODDS = "DONTCOME10ODDS",

  COME4ODDS = "COME4ODDS",
  COME5ODDS = "COME5ODDS",
  COME6ODDS = "COME6ODDS",
  COME8ODDS = "COME8ODDS",
  COME9ODDS = "COME9ODDS",
  COME10ODDS = "COME10ODDS",

  PLACE4 = "PLACE4",
  PLACE5 = "PLACE5",
  PLACE6 = "PLACE6",
  PLACE8 = "PLACE8",
  PLACE9 = "PLACE9",
  PLACE10 = "PLACE10",

  BUY4 = "BUY4",
  BUY10 = "BUY10",

  LAY4 = "LAY4",
  LAY5 = "LAY5",
  LAY6 = "LAY6",
  LAY8 = "LAY8",
  LAY9 = "LAY9",
  LAY10 = "LAY10",

  PROP_12 = "PROP_12",

  PUCKOFF = "PUCKOFF",
  PUCK4 = "PUCK4",
  PUCK5 = "PUCK5",
  PUCK6 = "PUCK6",
  PUCK8 = "PUCK8",
  PUCK9 = "PUCK9",
  PUCK10 = "PUCK10",

  DICE_START = "DICE_START",
  DICE_BOUNCE_TL = "DICE_BOUNCE_TL",
  DICE_BOUNCE_BR = "DICE_BOUNCE_BR",
  DICE_LAND_TL = "DICE_LAND_TL",
  DICE_LAND_BR = "DICE_LAND_BR",
  DICE_REST = "DICE_REST",
}

const COME_Y = -220;
const PLACE_Y = -180;
const LAY_Y = -360;
const PUCK_Y = -320;

const BOX_4 = -240;
const BOX_5 = -100;
const BOX_6 = 40;
const BOX_8 = 180;
const BOX_9 = 310;
const BOX_10 = 450;

const DCODDS_OFFSET = 60;

export const tableCoords: { [id: string]: Vector2 } = {
  PLAYER: new Vector2(0, 600),
  DEALER: new Vector2(0, -600),

  PASSLINE: new Vector2(-50, 235),
  PASSLINE_ODDS: new Vector2(-50, 325),

  DONTPASS: new Vector2(-35, 150),
  DONTPASSODDS: new Vector2(25, 150),

  FIELD: new Vector2(-100, 50),

  COME: new Vector2(0, -100),
  COME4: new Vector2(BOX_4, COME_Y),
  COME5: new Vector2(BOX_5, COME_Y),
  COME6: new Vector2(BOX_6, COME_Y),
  COME8: new Vector2(BOX_8, COME_Y),
  COME9: new Vector2(BOX_9, COME_Y),
  COME10: new Vector2(BOX_10, COME_Y),

  COME4ODDS: new Vector2(BOX_4, COME_Y + 30),
  COME5ODDS: new Vector2(BOX_5, COME_Y + 30),
  COME6ODDS: new Vector2(BOX_6, COME_Y + 30),
  COME8ODDS: new Vector2(BOX_8, COME_Y + 30),
  COME9ODDS: new Vector2(BOX_9, COME_Y + 30),
  COME10ODDS: new Vector2(BOX_10, COME_Y + 30),

  DONTCOME: new Vector2(586, -250),
  DONTCOME4: new Vector2(BOX_4, LAY_Y),
  DONTCOME5: new Vector2(BOX_5, LAY_Y),
  DONTCOME6: new Vector2(BOX_6, LAY_Y),
  DONTCOME8: new Vector2(BOX_8, LAY_Y),
  DONTCOME9: new Vector2(BOX_9, LAY_Y),
  DONTCOME10: new Vector2(BOX_10, LAY_Y),

  DONTCOME4ODDS: new Vector2(BOX_4 + DCODDS_OFFSET, LAY_Y),
  DONTCOME5ODDS: new Vector2(BOX_5 + DCODDS_OFFSET, LAY_Y),
  DONTCOME6ODDS: new Vector2(BOX_6 + DCODDS_OFFSET, LAY_Y),
  DONTCOME8ODDS: new Vector2(BOX_8 + DCODDS_OFFSET, LAY_Y),
  DONTCOME9ODDS: new Vector2(BOX_9 + DCODDS_OFFSET, LAY_Y),
  DONTCOME10ODDS: new Vector2(BOX_10 + DCODDS_OFFSET, LAY_Y),

  PLACE4: new Vector2(BOX_4, PLACE_Y),
  PLACE5: new Vector2(BOX_5, PLACE_Y),
  PLACE6: new Vector2(BOX_6, PLACE_Y),
  PLACE8: new Vector2(BOX_8, PLACE_Y),
  PLACE9: new Vector2(BOX_9, PLACE_Y),
  PLACE10: new Vector2(BOX_10, PLACE_Y),

  BUY4: new Vector2(BOX_4, PLACE_Y),
  BUY10: new Vector2(BOX_10, PLACE_Y),

  LAY4: new Vector2(BOX_4, LAY_Y),
  LAY5: new Vector2(BOX_5, LAY_Y),
  LAY6: new Vector2(BOX_6, LAY_Y),
  LAY8: new Vector2(BOX_8, LAY_Y),
  LAY9: new Vector2(BOX_9, LAY_Y),
  LAY10: new Vector2(BOX_10, LAY_Y),

  PROP_12: new Vector2(-430, 175),

  PUCKOFF: new Vector2(770, -380),
  PUCK4: new Vector2(BOX_4, PUCK_Y),
  PUCK5: new Vector2(BOX_5, PUCK_Y),
  PUCK6: new Vector2(BOX_6, PUCK_Y),
  PUCK8: new Vector2(BOX_8, PUCK_Y),
  PUCK9: new Vector2(BOX_9, PUCK_Y),
  PUCK10: new Vector2(BOX_10, PUCK_Y),

  DICE_START: new Vector2(-1000, -400),
  DICE_BOUNCE_TL: new Vector2(840, -230),
  DICE_BOUNCE_BR: new Vector2(840, 270),
  DICE_LAND_TL: new Vector2(-250, -100),
  DICE_LAND_BR: new Vector2(700, 350),
  DICE_REST: new Vector2(-650, -300),
};
